### ISSUE TITLE
ComputeAlleleCountsAndHistograms: too small memory buffer size for writing

### ISSUE THREAD

**Issue by jjfarrell** [statgen/bravo#8]
ComputeAlleleCountsAndHistograms is generating an error:

too small memory buffer size for writing

Is there a solution for this? Any suggestions?

**Comment by dtaliun** [comment]
In `aux.cpp` source file, try to increase the BUFFER_SIZE on line:
```
const unsigned int BUFFER_SIZE = 32768u;
```

**Comment by jjfarrell** [comment]
Thanks! That worked.  I think we have some large SVs in the VCF that were triggering the error.
